name: Scheduled Ping to Render Server
on:
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  pinger_job:
    name: A job to ping
    runs-on: ubuntu-latest
    env:
      URL: ${{ secrets.URL }}
      METHOD: GET  
    steps:
      - id: ping
        uses: sisodiya2421/pinger@master
